### ISSUE TITLE
Add option to output EPSS scores for Grype report findings to CSV & YAML

### ISSUE THREAD

**Issue by cleong14** [gatecheckdev/gatecheck#46]
Add an option to output EPSS scores for Grype report findings to a CSV and/or YAML file.

**Comment by Driste** [comment]
What about a way to export any tables prints from gatecheck into a csv using go templates? I know a bunch of the scanning tools support something simular, here's grype's: https://github.com/anchore/grype#using-templates

Example for a csv template: https://github.com/anchore/grype/blob/main/templates/csv.tmpl
